export const initialState = {
  user: {
    user_id: null,
    name: null,
    last_name1: "",
    last_name2: "",
    email: null,
    phone: null,
    id_province: null,
    id_canton: null,
    id_parish: null,
    address_ref: null,
    main_street: null,
    street_1_sec: null,
    street_2_sec: null,
  },
  pet: {
    name: null,
    birth: null,
    sex: null,
    castrated: null,
    specie: null,
    race: null,
    characteristic: null,
  },
  photes: [],
};
