export const initialState = {
  user: {
    email: null,
    email_verified_at: null,
    id_canton: null,
    canton: null,
    province: null,
    last_name1: null,
    last_name2: null,
    name: null,
    phone: null,
    profile_photo_url: null,
    profile_photo_path: null,
    user_id: null,
    api_token: null,
    id_province: null,
    parish: null,
    id_parish: null,
    address_ref: null,
    main_street: null,
    street_1_sec: null,
    street_2_sec: null,
    pet: [],
  },
};
